<a href="https://colab.research.google.com/github/jjonhwa/DeepLearning.AI-TensorFlow/blob/main/30_S%2BP_Week_2_Lesson_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [44]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [46]:
dataset = tf.data.Dataset.range(10)

for val in dataset :
  print(val.numpy())

0
1
2
3
4
5
6
7
8
9


In [48]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift = 1) # dataset을 5개씩 한 묶음으로 한칸씩 움직인다.

for window_dataset in dataset :
  for val in window_dataset :
    print(val.numpy(), end = ' ')
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 
6 7 8 9 
7 8 9 
8 9 
9 


In [50]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift = 1, drop_remainder = True) # drop_remainder : 5개 이하로 남아있으면 drop한다.

for window_dataset in dataset :
  for val in window_dataset :
    print(val.numpy(), end = " ")
  print()

0 1 2 3 4 
1 2 3 4 5 
2 3 4 5 6 
3 4 5 6 7 
4 5 6 7 8 
5 6 7 8 9 


In [52]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift = 1, drop_remainder = True)
dataset = dataset.flat_map(lambda window : window.batch(5)) # 각 윈도우들을 다시 5개씩 batch해준다.

for window in dataset : 
  print(window.numpy())

[0 1 2 3 4]
[1 2 3 4 5]
[2 3 4 5 6]
[3 4 5 6 7]
[4 5 6 7 8]
[5 6 7 8 9]


In [55]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift = 1, drop_remainder = True)
dataset = dataset.flat_map(lambda window : window.batch(5))
dataset = dataset.map(lambda window: (window[:-1], window[-1:])) # 윈도우의 [:-1]값과 [-1:]값을 매핑시켜서 세트로 묶는다.

for x,y in dataset :
  print(x.numpy(), y.numpy())

[0 1 2 3] [4]
[1 2 3 4] [5]
[2 3 4 5] [6]
[3 4 5 6] [7]
[4 5 6 7] [8]
[5 6 7 8] [9]


In [56]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift = 1, drop_remainder = True)
dataset = dataset.flat_map(lambda window : window.batch(5))
dataset = dataset.map(lambda window : (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size = 10) # 데이터의 크가가 10이여서 10만큼으로 size를 주고 섞어준다.

for x, y in dataset :
  print(x.numpy(), y.numpy())

[2 3 4 5] [6]
[3 4 5 6] [7]
[0 1 2 3] [4]
[4 5 6 7] [8]
[1 2 3 4] [5]
[5 6 7 8] [9]


In [58]:
dataset = tf.data.Dataset.range(10)
dataset = dataset.window(5, shift = 1, drop_remainder = True)
dataset = dataset.flat_map(lambda window : window.batch(5))
dataset = dataset.map(lambda window : (window[:-1], window[-1:]))
dataset = dataset.shuffle(buffer_size = 10)
dataset = dataset.batch(3).prefetch(1) # prefetch는 현재 요소를 처리하는 동안 나중에 처리할 요소들에 대해 준비할 수 있게하여 지연 시간과 처리량을 향상시켜준다.

for x,y in dataset :
  print('x=', x.numpy())
  print('y=', y.numpy())

x= [[2 3 4 5]
 [1 2 3 4]
 [3 4 5 6]]
y= [[6]
 [5]
 [7]]
x= [[5 6 7 8]
 [4 5 6 7]
 [0 1 2 3]]
y= [[9]
 [8]
 [4]]
